/*
 * Tantalum cloud-board bootstrap firmware.
 *
 * Placeholders are replaced during USB provisioning. WiFi credentials are not
 * compiled into this sketch; the runtime opens BLE or SoftAP provisioning.
 */

#define TANTALUM_BOARD_ID {{BOARD_ID_LITERAL}}
#define TANTALUM_API_TOKEN {{API_TOKEN_LITERAL}}
#define TANTALUM_APPWRITE_ENDPOINT {{APPWRITE_ENDPOINT_LITERAL}}
#define TANTALUM_APPWRITE_PROJECT_ID {{APPWRITE_PROJECT_ID_LITERAL}}
#define TANTALUM_DEVICE_GATEWAY_FUNCTION_ID {{DEVICE_GATEWAY_FUNCTION_ID_LITERAL}}
#define TANTALUM_FIRMWARE_VERSION "1.0.0"
#define TANTALUM_FIRMWARE_ID "bootstrap"
#define TANTALUM_RUNTIME_VERSION "1.1.11"
#define TANTALUM_BUILD_EPOCH {{BUILD_EPOCH_LITERAL}}
#define TANTALUM_OTA_UPDATE_MODE {{OTA_UPDATE_MODE_LITERAL}}
#define TANTALUM_BOOTSTRAP_BUILD 1
#define TANTALUM_MQTT_REQUIRED {{MQTT_REQUIRED_LITERAL}}
#define TANTALUM_MQTT_HOST {{MQTT_HOST_LITERAL}}
#define TANTALUM_MQTT_PORT {{MQTT_PORT_LITERAL}}
#define TANTALUM_MQTT_USERNAME {{MQTT_USERNAME_LITERAL}}
#define TANTALUM_MQTT_PASSWORD {{MQTT_PASSWORD_LITERAL}}
#define TANTALUM_MQTT_TOPIC {{MQTT_TOPIC_LITERAL}}
#define TANTALUM_COMMAND_SECRET {{COMMAND_SECRET_LITERAL}}
#define TANTALUM_TLS_CA_CERT {{TLS_CA_CERT_LITERAL}}
#define TANTALUM_MQTT_CA_CERT {{MQTT_CA_CERT_LITERAL}}
#define TANTALUM_PROVISIONING_POP {{PROVISIONING_POP_LITERAL}}
#define TANTALUM_PROVISIONING_SERVICE_NAME {{PROVISIONING_SERVICE_NAME_LITERAL}}
#define TANTALUM_WIFI_HOSTNAME {{WIFI_HOSTNAME_LITERAL}}

{{MQTT_INCLUDE_LINE}}
#include "TantalumCloudRuntime.h"

void setup() {
  TantalumCloud.begin();
}

void loop() {
  TantalumCloud.loop();
  delay(10);
}
